"""empty message

Revision ID: 1a3bbcfb82de
Revises: ef0939ff2e78
Create Date: 2018-12-16 13:12:03.770916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3bbcfb82de'
down_revision = 'ef0939ff2e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article_tag', 'jq_tag', ['jq_tag.tid'], ['tid'])
    op.create_foreign_key(None, 'article_tag', 'jq_article', ['jq_article.aid'], ['aid'])
    op.create_foreign_key(None, 'jq_article', 'jq_article_category', ['cat_id'], ['cat_id'])
    op.create_foreign_key(None, 'jq_article', 'jq_user', ['author_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    # ### end Alembic commands ###
