"""empty message

Revision ID: 5454e9ab0750
Revises: a3a95855e880
Create Date: 2018-11-25 15:11:03.854293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5454e9ab0750'
down_revision = 'a3a95855e880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jq_user', sa.Column('_password', sa.String(length=100), nullable=False))
    op.add_column('jq_user', sa.Column('reg_time', sa.DateTime(), nullable=True))
    op.drop_column('jq_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jq_user', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('jq_user', 'reg_time')
    op.drop_column('jq_user', '_password')
    # ### end Alembic commands ###
