"""empty message

Revision ID: 869a8426901e
Revises: b4f094d9587f
Create Date: 2018-12-07 20:42:26.684814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '869a8426901e'
down_revision = 'b4f094d9587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jq_article', sa.Column('description', sa.String(length=512), nullable=False))
    op.create_foreign_key(None, 'jq_article', 'jq_user', ['author_id'], ['uid'])
    op.create_foreign_key(None, 'jq_article', 'jq_article_category', ['cat_id'], ['cat_id'])
    op.drop_column('jq_article', 'digest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jq_article', sa.Column('digest', mysql.VARCHAR(length=512), nullable=False))
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_column('jq_article', 'description')
    # ### end Alembic commands ###
