"""empty message

Revision ID: 9911c720f982
Revises: 869a8426901e
Create Date: 2018-12-07 20:45:33.253088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9911c720f982'
down_revision = '869a8426901e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'jq_article', 'jq_user', ['author_id'], ['uid'])
    op.create_foreign_key(None, 'jq_article', 'jq_article_category', ['cat_id'], ['cat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    # ### end Alembic commands ###
