"""empty message

Revision ID: a3a95855e880
Revises: 17e6c4de9562
Create Date: 2018-11-25 13:51:08.568152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a95855e880'
down_revision = '17e6c4de9562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jq_user', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'jq_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jq_user', type_='unique')
    op.drop_column('jq_user', 'email')
    # ### end Alembic commands ###
