"""empty message

Revision ID: b557bf381aa1
Revises: 33824a7b9265
Create Date: 2018-12-16 21:16:42.062556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b557bf381aa1'
down_revision = '33824a7b9265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article_tag', 'jq_tag', ['jq_tag.tid'], ['tid'])
    op.create_foreign_key(None, 'article_tag', 'jq_article', ['jq_article.aid'], ['aid'])
    op.create_foreign_key(None, 'jq_article', 'jq_user', ['author_id'], ['uid'])
    op.create_foreign_key(None, 'jq_article', 'jq_article_category', ['cat_id'], ['cat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    # ### end Alembic commands ###
