"""empty message

Revision ID: ef0939ff2e78
Revises: 9911c720f982
Create Date: 2018-12-16 13:04:38.464757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef0939ff2e78'
down_revision = '9911c720f982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jq_tag',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.SmallInteger(), nullable=True),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('article_tag',
    sa.Column('jq_article.aid', sa.Integer(), nullable=False),
    sa.Column('jq_tag.tid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jq_article.aid'], ['jq_article.aid'], ),
    sa.ForeignKeyConstraint(['jq_tag.tid'], ['jq_tag.tid'], ),
    sa.PrimaryKeyConstraint('jq_article.aid', 'jq_tag.tid')
    )
    op.add_column('jq_article', sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('jq_article', sa.Column('allowcomments', sa.Integer(), nullable=True))
    op.add_column('jq_article', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('jq_article', sa.Column('editor', sa.Text(), nullable=False))
    op.add_column('jq_article', sa.Column('keywords', sa.String(length=64), nullable=False))
    op.add_column('jq_article', sa.Column('picture', sa.String(length=255), nullable=True))
    op.add_column('jq_article', sa.Column('shorttitle', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'jq_article', 'jq_article_category', ['cat_id'], ['cat_id'])
    op.create_foreign_key(None, 'jq_article', 'jq_user', ['author_id'], ['uid'])
    op.drop_column('jq_article', 'list_image_url')
    op.drop_column('jq_article', 'id')
    op.drop_column('jq_article', 'content')
    op.drop_column('jq_article_category', 'template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jq_article_category', sa.Column('template', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('jq_article', sa.Column('content', mysql.TEXT(), nullable=False))
    op.add_column('jq_article', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('jq_article', sa.Column('list_image_url', mysql.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_column('jq_article', 'shorttitle')
    op.drop_column('jq_article', 'picture')
    op.drop_column('jq_article', 'keywords')
    op.drop_column('jq_article', 'editor')
    op.drop_column('jq_article', 'create_time')
    op.drop_column('jq_article', 'allowcomments')
    op.drop_column('jq_article', 'aid')
    op.drop_table('article_tag')
    op.drop_table('jq_tag')
    # ### end Alembic commands ###
